AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  Create a wordpress installation on the LAMP stack using an EC2 instance

Parameters:
  KeyPairName:
    Description: A KeyPair to enable SSH to the EC2 instance.
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: EC2 instance type for the WebServer
    Type: String
    Default: t2.micro
    AllowedValues:
    - t1.micro
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    ConstraintDescription: Must be a valid EC2 instance type.
  SSHWhiteListIP:
    Description: The IP address range(CIDR) that can be used to SSH to the EC2 instances.
    Type: String
    Default: 0.0.0.0/0
    MinLength: 9
    MaxLength: 18
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.
  DBName:
    Description: The WordPress database name.
    Type: String
    Default: wordpressdb
    MinLength: 1
    MaxLength: 64
    AllowedPattern: '[a-zA-Z][a-zA-Z0-0]*'
    ConstraintDescription: Must contain only letter and numbers.
  DBUser:
    NoEcho: 'true'
    Description: The WordPress database admin username
    Type: String
    MinLength: 1
    MaxLength: 16
    AllowedPattern: '[a-zA-Z][a-zA-Z0-0]*'
    ConstraintDescription: Must contain only letter and numbers.
  DBPassword:
    NoEcho: 'true'
    Description: 'The WordPress database admin password'
    Type: String
    MinLength: 8
    MaxLength: 41
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: Must contain only alphanumeric characters
  DBRootPassword
    NoEcho: 'true'
    Description: 'The MYSQL root password'
    Type: String
    MinLength: 8
    MaxLength: 41
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: Must contain only alphanumeric characters

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: >-
        Enable HTTP access via port 80 and SSH at 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: !Ref SSHWhiteListIP
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHWhiteListIP
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-047a51fa27710816e
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref WebServerSecurityGroup
      KeyName: !Ref KeyPairName
    Metadata:
      Instance:
        Description: A sample EC2 instance
  IPAddress:
    Type: AWS::EC2::EIP
  IPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref WebServer
      EIP: !Ref IPAddress

Outputs:
  WebsiteUrl:
    Value: !Join
      - ''
      - - 'http://'
        - !GetAtt
          - WebServer
          - PublicDnsName
        - /wordpress
    Description: Wordpress Website URL
  OutputDNS:
    Value:
      !GetAtt WebServer.PublicDnsName
  OutputWebServer:
    Value:
      !Ref WebServer